# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  webdriver_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 5900:5900
    # open vnc://localhost:5900 (password: secret)
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webdriver_chrome
    environment:
      PG_PASSWORD: password
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
